# Generated by Django 5.0.6 on 2024-06-11 03:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('numero_mesa', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)], verbose_name='Numero de mesa')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto', models.CharField(verbose_name='Objeto')),
                ('nombre_del_producto', models.CharField(verbose_name='Nombre del producto')),
                ('subtipo', models.CharField(verbose_name='Tipo de comida/bebida')),
                ('descripcion', models.CharField(verbose_name='Descripción')),
                ('precio', models.IntegerField(verbose_name='Precio')),
            ],
        ),
    ]
